/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mad.views;

import mad.cards.CardFactory;

/**
 *
 * @author Francois
 */
public class MenuPartieSolo extends javax.swing.JFrame {

    /**
     * Creates new form MenuPartieSolo
     */
    public MenuPartieSolo() {
        initComponents();
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPartieSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPartieSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPartieSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPartieSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        cboEnsemble.setModel(new javax.swing.DefaultComboBoxModel(CardFactory.getCardSetNames().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlParametresSolo = new javax.swing.JPanel();
        lblPointsVie = new javax.swing.JLabel();
        lblNbOpposants = new javax.swing.JLabel();
        lblEnsemble = new javax.swing.JLabel();
        cboPointsVie = new javax.swing.JComboBox();
        cboNbOpposants = new javax.swing.JComboBox();
        cboEnsemble = new javax.swing.JComboBox();
        lblParamatresSolo = new javax.swing.JLabel();
        btnDemarrer = new javax.swing.JButton();
        btnDemarrer1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("M.A.D. Partie solo");

        pnlParametresSolo.setBackground(new java.awt.Color(153, 153, 255));

        lblPointsVie.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPointsVie.setText("Points de vie :");

        lblNbOpposants.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNbOpposants.setText("Nombre de joueurs :");

        lblEnsemble.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEnsemble.setText("Ensemble de cartes :");

        cboPointsVie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", " " }));

        cboNbOpposants.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4" }));

        lblParamatresSolo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblParamatresSolo.setText("Paramètres de la partie");

        btnDemarrer.setText("Annuler");
        btnDemarrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDemarrerMouseClicked(evt);
            }
        });

        btnDemarrer1.setText("Lancer la partie");
        btnDemarrer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDemarrer1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlParametresSoloLayout = new javax.swing.GroupLayout(pnlParametresSolo);
        pnlParametresSolo.setLayout(pnlParametresSoloLayout);
        pnlParametresSoloLayout.setHorizontalGroup(
            pnlParametresSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametresSoloLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlParametresSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblParamatresSolo)
                    .addGroup(pnlParametresSoloLayout.createSequentialGroup()
                        .addGroup(pnlParametresSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPointsVie)
                            .addComponent(lblNbOpposants)
                            .addComponent(lblEnsemble)
                            .addComponent(btnDemarrer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(pnlParametresSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlParametresSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboEnsemble, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboNbOpposants, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboPointsVie, 0, 99, Short.MAX_VALUE))
                            .addComponent(btnDemarrer1))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        pnlParametresSoloLayout.setVerticalGroup(
            pnlParametresSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametresSoloLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblParamatresSolo)
                .addGap(26, 26, 26)
                .addGroup(pnlParametresSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPointsVie)
                    .addComponent(cboPointsVie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlParametresSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNbOpposants)
                    .addComponent(cboNbOpposants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlParametresSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnsemble)
                    .addComponent(cboEnsemble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlParametresSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDemarrer)
                    .addComponent(btnDemarrer1))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        lblNbOpposants.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlParametresSolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlParametresSolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDemarrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemarrerMouseClicked
        this.setVisible(false);
        new MenuPrincipal().start();
        this.dispose();
    }//GEN-LAST:event_btnDemarrerMouseClicked

    private void btnDemarrer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemarrer1MouseClicked
        this.setVisible(false);
        new VuePartie(Integer.parseInt((String)cboNbOpposants.getSelectedItem()),
                Integer.parseInt((String)cboPointsVie.getSelectedItem()),
                CardFactory.getCardSet((String)cboEnsemble.getSelectedItem())).start();
        this.dispose();
    }//GEN-LAST:event_btnDemarrer1MouseClicked

    public void start() {
        final MenuPartieSolo me = this;
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                me.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDemarrer;
    private javax.swing.JButton btnDemarrer1;
    private javax.swing.JComboBox cboEnsemble;
    private javax.swing.JComboBox cboNbOpposants;
    private javax.swing.JComboBox cboPointsVie;
    private javax.swing.JLabel lblEnsemble;
    private javax.swing.JLabel lblNbOpposants;
    private javax.swing.JLabel lblParamatresSolo;
    private javax.swing.JLabel lblPointsVie;
    private javax.swing.JPanel pnlParametresSolo;
    // End of variables declaration//GEN-END:variables
}
