/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mad.views;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mad.cards.Card;
import mad.cards.CardSet;
import mad.game.Game;
import mad.game.Player;

/**
 *
 * @author Francois
 */
public class VuePartie extends javax.swing.JFrame {
    
    private final JFrame frame = this;
    private enum Phase {ATTAQUE, TARGETING, DEFENSE, PASSE, USINE, CONTINUER};
    private Game partie;
    private Phase phaseJeu;
    private int selection;
    private Color defaut = new Color(240, 240, 240);
    private Color actif = new Color(102, 255, 102);
    private Color attaque = new Color(255, 51, 51);

    /**
     * Creates new form VuePartie
     */
    public VuePartie() {
        initComponents();
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
    
    public VuePartie(int nbJoueur, int ptsVie, CardSet cards) {
        initComponents();
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        PnlCarteEnJeu.setBackground(defaut);
        pnlStatut.setBackground(defaut);
        pnlInformation.setBackground(defaut);
        lockAllPhase();
        partie = new Game(this,nbJoueur,ptsVie,cards);    
        updateInterfaceJeu();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlPartie = new javax.swing.JPanel();
        PnlAdversaire1 = new javax.swing.JPanel();
        lblJoueur2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblUsineDeux2 = new javax.swing.JLabel();
        lblUsineUn2 = new javax.swing.JLabel();
        lblRecherche2 = new javax.swing.JLabel();
        lblPtsVie2 = new javax.swing.JLabel();
        lblCarteEnMain2 = new javax.swing.JLabel();
        lblDommage2 = new javax.swing.JLabel();
        PnlAdversaire2 = new javax.swing.JPanel();
        lblJoueur3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPtsVie3 = new javax.swing.JLabel();
        lblCarteEnMain3 = new javax.swing.JLabel();
        lblUsineUn3 = new javax.swing.JLabel();
        lblUsineDeux3 = new javax.swing.JLabel();
        lblRecherche3 = new javax.swing.JLabel();
        lblDommage3 = new javax.swing.JLabel();
        PnlAdversaire3 = new javax.swing.JPanel();
        lblJoueur4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPtsVie4 = new javax.swing.JLabel();
        lblCarteEnMain4 = new javax.swing.JLabel();
        lblUsineUn4 = new javax.swing.JLabel();
        lblUsineDeux4 = new javax.swing.JLabel();
        lblRecherche4 = new javax.swing.JLabel();
        lblDommage4 = new javax.swing.JLabel();
        PnlInfoPersonnel = new javax.swing.JPanel();
        btnAction1 = new javax.swing.JButton();
        btnAction2 = new javax.swing.JButton();
        lblJoueur1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPtsVie1 = new javax.swing.JLabel();
        lblUsineUn1 = new javax.swing.JLabel();
        lblUsineDeux1 = new javax.swing.JLabel();
        lblRecherche1 = new javax.swing.JLabel();
        pnlCarte1 = new javax.swing.JPanel();
        lblNomCarte1 = new javax.swing.JLabel();
        lblImgCarte1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescriptionCarte1 = new javax.swing.JTextArea();
        pnlCarteChoisi = new javax.swing.JPanel();
        lblNomCarteChoisi = new javax.swing.JLabel();
        lblImgCarteChoisi = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescriptionCarteChoisi = new javax.swing.JTextArea();
        lblCarteChoisi = new javax.swing.JLabel();
        pnlCarte2 = new javax.swing.JPanel();
        lblNomCarte2 = new javax.swing.JLabel();
        lblImgCarte2 = new javax.swing.JLabel();
        jScrollPane77 = new javax.swing.JScrollPane();
        txtDescriptionCarte2 = new javax.swing.JTextArea();
        pnlCarte3 = new javax.swing.JPanel();
        lblNomCarte3 = new javax.swing.JLabel();
        jScrollPane78 = new javax.swing.JScrollPane();
        txtDescriptionCarte3 = new javax.swing.JTextArea();
        lblImgCarte3 = new javax.swing.JLabel();
        pnlCarte4 = new javax.swing.JPanel();
        lblNomCarte4 = new javax.swing.JLabel();
        lblImgCarte4 = new javax.swing.JLabel();
        jScrollPane79 = new javax.swing.JScrollPane();
        txtDescriptionCarte4 = new javax.swing.JTextArea();
        pnlCarte5 = new javax.swing.JPanel();
        lblNomCarte5 = new javax.swing.JLabel();
        lblImgCarte5 = new javax.swing.JLabel();
        jScrollPane87 = new javax.swing.JScrollPane();
        txtDescriptionCarte5 = new javax.swing.JTextArea();
        lblDommage1 = new javax.swing.JLabel();
        PnlCarteEnJeu = new javax.swing.JPanel();
        pnlCarteJeu = new javax.swing.JPanel();
        lblNomCarteJeu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescriptionCarteJeu = new javax.swing.JTextArea();
        lblCarteEnJeu = new javax.swing.JLabel();
        lblImgCarteJeu = new javax.swing.JLabel();
        pnlStatut = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEvenement = new javax.swing.JTextArea();
        pnlInformation = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblTour = new javax.swing.JLabel();
        lblPaquet = new javax.swing.JLabel();
        lblTalon = new javax.swing.JLabel();
        btnAbandonner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("M.A.D. Partie");
        setResizable(false);

        PnlPartie.setBackground(new java.awt.Color(153, 153, 255));
        PnlPartie.setPreferredSize(new java.awt.Dimension(880, 792));

        PnlAdversaire1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PnlAdversaire1.setEnabled(false);
        PnlAdversaire1.setPreferredSize(new java.awt.Dimension(485, 100));
        PnlAdversaire1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlAdversaire1MouseClicked(evt);
            }
        });

        lblJoueur2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJoueur2.setText("Joueur 2");

        jLabel1.setText("Points de vie : ");

        jLabel5.setText("Cartes en main:");

        lblUsineDeux2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineDeux2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsineUn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineUn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRecherche2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecherche2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPtsVie2.setText("0");

        lblCarteEnMain2.setText("0");

        lblDommage2.setForeground(new java.awt.Color(102, 0, 0));
        lblDommage2.setText("1");
        lblDommage2.setToolTipText("");

        javax.swing.GroupLayout PnlAdversaire1Layout = new javax.swing.GroupLayout(PnlAdversaire1);
        PnlAdversaire1.setLayout(PnlAdversaire1Layout);
        PnlAdversaire1Layout.setHorizontalGroup(
            PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJoueur2)
                    .addGroup(PnlAdversaire1Layout.createSequentialGroup()
                        .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCarteEnMain2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPtsVie2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDommage2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblUsineUn2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblUsineDeux2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRecherche2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PnlAdversaire1Layout.setVerticalGroup(
            PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsineUn2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecherche2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlAdversaire1Layout.createSequentialGroup()
                        .addComponent(lblJoueur2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblPtsVie2)
                            .addComponent(lblDommage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblCarteEnMain2)))
                    .addComponent(lblUsineDeux2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        lblDommage2.getAccessibleContext().setAccessibleDescription("");

        PnlAdversaire2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PnlAdversaire2.setEnabled(false);
        PnlAdversaire2.setPreferredSize(new java.awt.Dimension(99, 100));
        PnlAdversaire2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlAdversaire2MouseClicked(evt);
            }
        });

        lblJoueur3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJoueur3.setText("Joueur 3");

        jLabel2.setText("Points de vie : ");

        jLabel6.setText("Cartes en main:");

        lblPtsVie3.setText("0");

        lblCarteEnMain3.setText("0");

        lblUsineUn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineUn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsineDeux3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineDeux3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRecherche3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecherche3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDommage3.setForeground(new java.awt.Color(102, 0, 0));
        lblDommage3.setText("1");
        lblDommage3.setName("");

        javax.swing.GroupLayout PnlAdversaire2Layout = new javax.swing.GroupLayout(PnlAdversaire2);
        PnlAdversaire2.setLayout(PnlAdversaire2Layout);
        PnlAdversaire2Layout.setHorizontalGroup(
            PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlAdversaire2Layout.createSequentialGroup()
                        .addGroup(PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlAdversaire2Layout.createSequentialGroup()
                                .addComponent(lblPtsVie3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDommage3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCarteEnMain3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblJoueur3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblUsineUn3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsineDeux3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRecherche3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PnlAdversaire2Layout.setVerticalGroup(
            PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUsineUn3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUsineDeux3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRecherche3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlAdversaire2Layout.createSequentialGroup()
                        .addComponent(lblJoueur3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPtsVie3)
                            .addComponent(jLabel2)
                            .addComponent(lblDommage3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarteEnMain3)
                            .addComponent(jLabel6))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblPtsVie3.getAccessibleContext().setAccessibleName("");
        lblCarteEnMain3.getAccessibleContext().setAccessibleName("");

        PnlAdversaire3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PnlAdversaire3.setEnabled(false);
        PnlAdversaire3.setPreferredSize(new java.awt.Dimension(440, 100));
        PnlAdversaire3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlAdversaire3MouseClicked(evt);
            }
        });

        lblJoueur4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJoueur4.setText("Joueur 4");

        jLabel3.setText("Points de vie : ");

        jLabel7.setText("Cartes en main:");

        lblPtsVie4.setText("0");

        lblCarteEnMain4.setText("0");

        lblUsineUn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineUn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsineDeux4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineDeux4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRecherche4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecherche4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDommage4.setForeground(new java.awt.Color(102, 0, 0));
        lblDommage4.setText("1");

        javax.swing.GroupLayout PnlAdversaire3Layout = new javax.swing.GroupLayout(PnlAdversaire3);
        PnlAdversaire3.setLayout(PnlAdversaire3Layout);
        PnlAdversaire3Layout.setHorizontalGroup(
            PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJoueur4)
                    .addGroup(PnlAdversaire3Layout.createSequentialGroup()
                        .addGroup(PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarteEnMain4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlAdversaire3Layout.createSequentialGroup()
                                .addComponent(lblPtsVie4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDommage4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblUsineUn4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsineDeux4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRecherche4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PnlAdversaire3Layout.setVerticalGroup(
            PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlAdversaire3Layout.createSequentialGroup()
                        .addComponent(lblJoueur4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PnlAdversaire3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(PnlAdversaire3Layout.createSequentialGroup()
                                .addGroup(PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPtsVie4)
                                    .addComponent(lblDommage4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCarteEnMain4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUsineUn4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUsineDeux4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRecherche4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        PnlInfoPersonnel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PnlInfoPersonnel.setPreferredSize(new java.awt.Dimension(865, 10));

        btnAction1.setText("Jouer");
        btnAction1.setEnabled(false);
        btnAction1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAction1MouseClicked(evt);
            }
        });

        btnAction2.setText("Passer");
        btnAction2.setEnabled(false);

        lblJoueur1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJoueur1.setText("Joueur 1");

        jLabel4.setText("Points de vie : ");

        lblPtsVie1.setText("50");

        lblUsineUn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineUn1.setText("Usine 1");
        lblUsineUn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsineDeux1.setBackground(new java.awt.Color(204, 204, 204));
        lblUsineDeux1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineDeux1.setText("Usine 2");
        lblUsineDeux1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRecherche1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecherche1.setText("Recherche");
        lblRecherche1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlCarte1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pnlCarte1.setEnabled(false);
        pnlCarte1.setPreferredSize(new java.awt.Dimension(110, 195));
        pnlCarte1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCarte1MouseClicked(evt);
            }
        });

        lblNomCarte1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblImgCarte1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImgCarte1.setMaximumSize(new java.awt.Dimension(85, 75));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDescriptionCarte1.setBackground(new java.awt.Color(240, 240, 240));
        txtDescriptionCarte1.setColumns(20);
        txtDescriptionCarte1.setEditable(false);
        txtDescriptionCarte1.setFont(new java.awt.Font("Monospaced", 0, 8)); // NOI18N
        txtDescriptionCarte1.setLineWrap(true);
        txtDescriptionCarte1.setRows(3);
        txtDescriptionCarte1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtDescriptionCarte1);

        javax.swing.GroupLayout pnlCarte1Layout = new javax.swing.GroupLayout(pnlCarte1);
        pnlCarte1.setLayout(pnlCarte1Layout);
        pnlCarte1Layout.setHorizontalGroup(
            pnlCarte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCarte1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNomCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImgCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlCarte1Layout.setVerticalGroup(
            pnlCarte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarte1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImgCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        pnlCarteChoisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImgCarteChoisi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setHorizontalScrollBar(null);

        txtDescriptionCarteChoisi.setBackground(new java.awt.Color(240, 240, 240));
        txtDescriptionCarteChoisi.setColumns(20);
        txtDescriptionCarteChoisi.setEditable(false);
        txtDescriptionCarteChoisi.setLineWrap(true);
        txtDescriptionCarteChoisi.setRows(5);
        txtDescriptionCarteChoisi.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtDescriptionCarteChoisi);

        javax.swing.GroupLayout pnlCarteChoisiLayout = new javax.swing.GroupLayout(pnlCarteChoisi);
        pnlCarteChoisi.setLayout(pnlCarteChoisiLayout);
        pnlCarteChoisiLayout.setHorizontalGroup(
            pnlCarteChoisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarteChoisiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarteChoisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarteChoisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCarteChoisiLayout.createSequentialGroup()
                        .addGroup(pnlCarteChoisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomCarteChoisi)
                            .addComponent(lblImgCarteChoisi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCarteChoisiLayout.setVerticalGroup(
            pnlCarteChoisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarteChoisiLayout.createSequentialGroup()
                .addComponent(lblCarteChoisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomCarteChoisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImgCarteChoisi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCarte2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pnlCarte2.setEnabled(false);
        pnlCarte2.setPreferredSize(new java.awt.Dimension(110, 195));
        pnlCarte2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCarte2MouseClicked(evt);
            }
        });

        lblNomCarte2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblImgCarte2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImgCarte2.setMaximumSize(new java.awt.Dimension(85, 75));

        jScrollPane77.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane77.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDescriptionCarte2.setBackground(new java.awt.Color(240, 240, 240));
        txtDescriptionCarte2.setColumns(20);
        txtDescriptionCarte2.setEditable(false);
        txtDescriptionCarte2.setFont(new java.awt.Font("Monospaced", 0, 8)); // NOI18N
        txtDescriptionCarte2.setLineWrap(true);
        txtDescriptionCarte2.setRows(3);
        txtDescriptionCarte2.setWrapStyleWord(true);
        jScrollPane77.setViewportView(txtDescriptionCarte2);

        javax.swing.GroupLayout pnlCarte2Layout = new javax.swing.GroupLayout(pnlCarte2);
        pnlCarte2.setLayout(pnlCarte2Layout);
        pnlCarte2Layout.setHorizontalGroup(
            pnlCarte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarte2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgCarte2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane77, javax.swing.GroupLayout.DEFAULT_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomCarte2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlCarte2Layout.setVerticalGroup(
            pnlCarte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarte2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomCarte2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImgCarte2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane77)
                .addContainerGap())
        );

        pnlCarte3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pnlCarte3.setEnabled(false);
        pnlCarte3.setPreferredSize(new java.awt.Dimension(110, 195));
        pnlCarte3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCarte3MouseClicked(evt);
            }
        });

        lblNomCarte3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jScrollPane78.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane78.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane78.setPreferredSize(new java.awt.Dimension(85, 39));

        txtDescriptionCarte3.setBackground(new java.awt.Color(240, 240, 240));
        txtDescriptionCarte3.setColumns(20);
        txtDescriptionCarte3.setEditable(false);
        txtDescriptionCarte3.setFont(new java.awt.Font("Monospaced", 0, 8)); // NOI18N
        txtDescriptionCarte3.setLineWrap(true);
        txtDescriptionCarte3.setRows(3);
        txtDescriptionCarte3.setWrapStyleWord(true);
        jScrollPane78.setViewportView(txtDescriptionCarte3);

        lblImgCarte3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImgCarte3.setMaximumSize(new java.awt.Dimension(85, 75));

        javax.swing.GroupLayout pnlCarte3Layout = new javax.swing.GroupLayout(pnlCarte3);
        pnlCarte3.setLayout(pnlCarte3Layout);
        pnlCarte3Layout.setHorizontalGroup(
            pnlCarte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarte3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCarte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblNomCarte3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane78, javax.swing.GroupLayout.DEFAULT_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImgCarte3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCarte3Layout.setVerticalGroup(
            pnlCarte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarte3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomCarte3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImgCarte3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCarte4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pnlCarte4.setEnabled(false);
        pnlCarte4.setPreferredSize(new java.awt.Dimension(110, 195));
        pnlCarte4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCarte4MouseClicked(evt);
            }
        });

        lblNomCarte4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblImgCarte4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImgCarte4.setMaximumSize(new java.awt.Dimension(85, 75));

        jScrollPane79.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane79.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDescriptionCarte4.setBackground(new java.awt.Color(240, 240, 240));
        txtDescriptionCarte4.setColumns(20);
        txtDescriptionCarte4.setEditable(false);
        txtDescriptionCarte4.setFont(new java.awt.Font("Monospaced", 0, 8)); // NOI18N
        txtDescriptionCarte4.setLineWrap(true);
        txtDescriptionCarte4.setRows(3);
        txtDescriptionCarte4.setWrapStyleWord(true);
        jScrollPane79.setViewportView(txtDescriptionCarte4);

        javax.swing.GroupLayout pnlCarte4Layout = new javax.swing.GroupLayout(pnlCarte4);
        pnlCarte4.setLayout(pnlCarte4Layout);
        pnlCarte4Layout.setHorizontalGroup(
            pnlCarte4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarte4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarte4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgCarte4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane79, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomCarte4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlCarte4Layout.setVerticalGroup(
            pnlCarte4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarte4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomCarte4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImgCarte4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane79)
                .addContainerGap())
        );

        pnlCarte5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pnlCarte5.setEnabled(false);
        pnlCarte5.setPreferredSize(new java.awt.Dimension(110, 195));
        pnlCarte5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCarte5MouseClicked(evt);
            }
        });

        lblNomCarte5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblImgCarte5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImgCarte5.setMaximumSize(new java.awt.Dimension(85, 75));

        jScrollPane87.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane87.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDescriptionCarte5.setBackground(new java.awt.Color(240, 240, 240));
        txtDescriptionCarte5.setColumns(20);
        txtDescriptionCarte5.setEditable(false);
        txtDescriptionCarte5.setFont(new java.awt.Font("Monospaced", 0, 8)); // NOI18N
        txtDescriptionCarte5.setLineWrap(true);
        txtDescriptionCarte5.setRows(3);
        txtDescriptionCarte5.setWrapStyleWord(true);
        jScrollPane87.setViewportView(txtDescriptionCarte5);

        javax.swing.GroupLayout pnlCarte5Layout = new javax.swing.GroupLayout(pnlCarte5);
        pnlCarte5.setLayout(pnlCarte5Layout);
        pnlCarte5Layout.setHorizontalGroup(
            pnlCarte5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarte5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarte5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgCarte5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane87, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomCarte5, javax.swing.GroupLayout.DEFAULT_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlCarte5Layout.setVerticalGroup(
            pnlCarte5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarte5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomCarte5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImgCarte5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane87)
                .addContainerGap())
        );

        lblDommage1.setForeground(new java.awt.Color(102, 0, 0));
        lblDommage1.setText("1");

        javax.swing.GroupLayout PnlInfoPersonnelLayout = new javax.swing.GroupLayout(PnlInfoPersonnel);
        PnlInfoPersonnel.setLayout(PnlInfoPersonnelLayout);
        PnlInfoPersonnelLayout.setHorizontalGroup(
            PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCarteChoisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                        .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAction2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                                .addComponent(btnAction1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJoueur1)
                                    .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPtsVie1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDommage1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(lblUsineUn1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUsineDeux1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRecherche1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(pnlCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlCarte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlCarte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlCarte4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlCarte5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PnlInfoPersonnelLayout.setVerticalGroup(
            PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCarteChoisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                        .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                                .addComponent(btnAction1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAction2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblUsineDeux1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRecherche1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUsineUn1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                                .addComponent(lblJoueur1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lblPtsVie1)
                                    .addComponent(lblDommage1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlCarte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCarte2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCarte3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCarte5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCarte4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        PnlCarteEnJeu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PnlCarteEnJeu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlCarteEnJeuMouseClicked(evt);
            }
        });

        pnlCarteJeu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDescriptionCarteJeu.setBackground(new java.awt.Color(240, 240, 240));
        txtDescriptionCarteJeu.setColumns(20);
        txtDescriptionCarteJeu.setEditable(false);
        txtDescriptionCarteJeu.setLineWrap(true);
        txtDescriptionCarteJeu.setRows(5);
        txtDescriptionCarteJeu.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtDescriptionCarteJeu);

        lblImgCarteJeu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlCarteJeuLayout = new javax.swing.GroupLayout(pnlCarteJeu);
        pnlCarteJeu.setLayout(pnlCarteJeuLayout);
        pnlCarteJeuLayout.setHorizontalGroup(
            pnlCarteJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarteJeuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarteJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCarteJeuLayout.createSequentialGroup()
                        .addComponent(lblCarteEnJeu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomCarteJeu))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCarteJeuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlCarteJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImgCarteJeu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlCarteJeuLayout.setVerticalGroup(
            pnlCarteJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarteJeuLayout.createSequentialGroup()
                .addComponent(lblCarteEnJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomCarteJeu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImgCarteJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        lblNomCarteJeu.getAccessibleContext().setAccessibleName("lblNomCarteJeu");

        javax.swing.GroupLayout PnlCarteEnJeuLayout = new javax.swing.GroupLayout(PnlCarteEnJeu);
        PnlCarteEnJeu.setLayout(PnlCarteEnJeuLayout);
        PnlCarteEnJeuLayout.setHorizontalGroup(
            PnlCarteEnJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCarteEnJeuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCarteJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlCarteEnJeuLayout.setVerticalGroup(
            PnlCarteEnJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCarteEnJeuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCarteJeu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlStatut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pnlStatut.setPreferredSize(new java.awt.Dimension(865, 75));
        pnlStatut.setVerifyInputWhenFocusTarget(false);

        txtEvenement.setBackground(new java.awt.Color(240, 240, 240));
        txtEvenement.setColumns(20);
        txtEvenement.setEditable(false);
        txtEvenement.setRows(3);
        txtEvenement.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtEvenement);

        javax.swing.GroupLayout pnlStatutLayout = new javax.swing.GroupLayout(pnlStatut);
        pnlStatut.setLayout(pnlStatutLayout);
        pnlStatutLayout.setHorizontalGroup(
            pnlStatutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlStatutLayout.setVerticalGroup(
            pnlStatutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInformation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel24.setText("Tour:");

        jLabel28.setText("Paquet :");

        jLabel29.setText("Talon :");

        lblTour.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTour.setText("0");

        lblPaquet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPaquet.setText("0");

        lblTalon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTalon.setText("0");

        btnAbandonner.setText("Abandonner");
        btnAbandonner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbandonnerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlInformationLayout = new javax.swing.GroupLayout(pnlInformation);
        pnlInformation.setLayout(pnlInformationLayout);
        pnlInformationLayout.setHorizontalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbandonner, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTour, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTalon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPaquet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlInformationLayout.setVerticalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblTour))
                .addGap(18, 18, 18)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblPaquet))
                .addGap(18, 18, 18)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblTalon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbandonner)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlPartieLayout = new javax.swing.GroupLayout(PnlPartie);
        PnlPartie.setLayout(PnlPartieLayout);
        PnlPartieLayout.setHorizontalGroup(
            PnlPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPartieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStatut, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                    .addComponent(PnlInfoPersonnel, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                    .addGroup(PnlPartieLayout.createSequentialGroup()
                        .addComponent(PnlCarteEnJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PnlAdversaire2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                            .addComponent(PnlAdversaire3, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                            .addComponent(PnlAdversaire1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        PnlPartieLayout.setVerticalGroup(
            PnlPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPartieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlPartieLayout.createSequentialGroup()
                        .addComponent(PnlAdversaire1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PnlAdversaire2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(PnlAdversaire3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PnlCarteEnJeu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnlInfoPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPartie, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPartie, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PnlCarteEnJeuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlCarteEnJeuMouseClicked

    }//GEN-LAST:event_PnlCarteEnJeuMouseClicked

    private void btnAbandonnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbandonnerMouseClicked
        int choix = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr de vouloir abandonner la partie?");
        
        if (choix == 0) {
            this.setVisible(false);
            new MenuPrincipal().start();
            this.dispose();
        } 
    }//GEN-LAST:event_btnAbandonnerMouseClicked

    private void pnlCarte1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarte1MouseClicked
        if (pnlCarte1.isEnabled()) {
            selection = 0;
            btnAction1.setEnabled(true);
            
            lblCarteChoisi.setText(lblNomCarte1.getText());
            lblImgCarteChoisi.setIcon(lblImgCarte1.getIcon());
            txtDescriptionCarteChoisi.setText(txtDescriptionCarte1.getText());
        }
    }//GEN-LAST:event_pnlCarte1MouseClicked

    private void pnlCarte2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarte2MouseClicked
        if (pnlCarte2.isEnabled()) {
            selection = 1;
            btnAction1.setEnabled(true);
            
            lblCarteChoisi.setText(lblNomCarte2.getText());
            lblImgCarteChoisi.setIcon(lblImgCarte2.getIcon());
            txtDescriptionCarteChoisi.setText(txtDescriptionCarte2.getText());
        }
    }//GEN-LAST:event_pnlCarte2MouseClicked

    private void pnlCarte3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarte3MouseClicked
        if (pnlCarte3.isEnabled()) {
            selection = 2;
            btnAction1.setEnabled(true);
            
            lblCarteChoisi.setText(lblNomCarte3.getText());
            lblImgCarteChoisi.setIcon(lblImgCarte3.getIcon());
            txtDescriptionCarteChoisi.setText(txtDescriptionCarte3.getText());
        }
    }//GEN-LAST:event_pnlCarte3MouseClicked

    private void pnlCarte4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarte4MouseClicked
        if (pnlCarte4.isEnabled()) {
            selection = 3;
            btnAction1.setEnabled(true);
            
            lblCarteChoisi.setText(lblNomCarte4.getText());
            lblImgCarteChoisi.setIcon(lblImgCarte4.getIcon());
            txtDescriptionCarteChoisi.setText(txtDescriptionCarte4.getText());
        }
    }//GEN-LAST:event_pnlCarte4MouseClicked

    private void pnlCarte5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarte5MouseClicked
        if (pnlCarte5.isEnabled()) {
            selection = 4;
            btnAction1.setEnabled(true);
            
            lblCarteChoisi.setText(lblNomCarte5.getText());
            lblImgCarteChoisi.setIcon(lblImgCarte5.getIcon());
            txtDescriptionCarteChoisi.setText(txtDescriptionCarte5.getText());
        }
    }//GEN-LAST:event_pnlCarte5MouseClicked

    private void PnlAdversaire1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlAdversaire1MouseClicked
        if (PnlAdversaire1.isEnabled()) {
            partie.playerSelectTarget(1);
        }
    }//GEN-LAST:event_PnlAdversaire1MouseClicked

    private void PnlAdversaire2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlAdversaire2MouseClicked
        if (PnlAdversaire2.isEnabled()) {
            partie.playerSelectTarget(2);
        }
    }//GEN-LAST:event_PnlAdversaire2MouseClicked

    private void PnlAdversaire3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlAdversaire3MouseClicked
        if (PnlAdversaire3.isEnabled()) {
            partie.playerSelectTarget(3);
        }
    }//GEN-LAST:event_PnlAdversaire3MouseClicked

    private void btnAction1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAction1MouseClicked
        if (phaseJeu == Phase.PASSE) {
            //partie.????
            lockAllPhase();
            btnAction1.setText("Jouer");
            
        } else if (phaseJeu == Phase.CONTINUER) {
            lockAllPhase();
            partie.nextRound();
        }
        else {
            lockAllPhase();
            partie.playerPlayCard(selection);
        }
        
    }//GEN-LAST:event_btnAction1MouseClicked

    public void start() {
        final VuePartie me = this;
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                me.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlAdversaire1;
    private javax.swing.JPanel PnlAdversaire2;
    private javax.swing.JPanel PnlAdversaire3;
    private javax.swing.JPanel PnlCarteEnJeu;
    private javax.swing.JPanel PnlInfoPersonnel;
    private javax.swing.JPanel PnlPartie;
    private javax.swing.JButton btnAbandonner;
    private javax.swing.JButton btnAction1;
    private javax.swing.JButton btnAction2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane77;
    private javax.swing.JScrollPane jScrollPane78;
    private javax.swing.JScrollPane jScrollPane79;
    private javax.swing.JScrollPane jScrollPane87;
    private javax.swing.JLabel lblCarteChoisi;
    private javax.swing.JLabel lblCarteEnJeu;
    private javax.swing.JLabel lblCarteEnMain2;
    private javax.swing.JLabel lblCarteEnMain3;
    private javax.swing.JLabel lblCarteEnMain4;
    private javax.swing.JLabel lblDommage1;
    private javax.swing.JLabel lblDommage2;
    private javax.swing.JLabel lblDommage3;
    private javax.swing.JLabel lblDommage4;
    private javax.swing.JLabel lblImgCarte1;
    private javax.swing.JLabel lblImgCarte2;
    private javax.swing.JLabel lblImgCarte3;
    private javax.swing.JLabel lblImgCarte4;
    private javax.swing.JLabel lblImgCarte5;
    private javax.swing.JLabel lblImgCarteChoisi;
    private javax.swing.JLabel lblImgCarteJeu;
    private javax.swing.JLabel lblJoueur1;
    private javax.swing.JLabel lblJoueur2;
    private javax.swing.JLabel lblJoueur3;
    private javax.swing.JLabel lblJoueur4;
    private javax.swing.JLabel lblNomCarte1;
    private javax.swing.JLabel lblNomCarte2;
    private javax.swing.JLabel lblNomCarte3;
    private javax.swing.JLabel lblNomCarte4;
    private javax.swing.JLabel lblNomCarte5;
    private javax.swing.JLabel lblNomCarteChoisi;
    private javax.swing.JLabel lblNomCarteJeu;
    private javax.swing.JLabel lblPaquet;
    private javax.swing.JLabel lblPtsVie1;
    private javax.swing.JLabel lblPtsVie2;
    private javax.swing.JLabel lblPtsVie3;
    private javax.swing.JLabel lblPtsVie4;
    private javax.swing.JLabel lblRecherche1;
    private javax.swing.JLabel lblRecherche2;
    private javax.swing.JLabel lblRecherche3;
    private javax.swing.JLabel lblRecherche4;
    private javax.swing.JLabel lblTalon;
    private javax.swing.JLabel lblTour;
    private javax.swing.JLabel lblUsineDeux1;
    private javax.swing.JLabel lblUsineDeux2;
    private javax.swing.JLabel lblUsineDeux3;
    private javax.swing.JLabel lblUsineDeux4;
    private javax.swing.JLabel lblUsineUn1;
    private javax.swing.JLabel lblUsineUn2;
    private javax.swing.JLabel lblUsineUn3;
    private javax.swing.JLabel lblUsineUn4;
    private javax.swing.JPanel pnlCarte1;
    private javax.swing.JPanel pnlCarte2;
    private javax.swing.JPanel pnlCarte3;
    private javax.swing.JPanel pnlCarte4;
    private javax.swing.JPanel pnlCarte5;
    private javax.swing.JPanel pnlCarteChoisi;
    private javax.swing.JPanel pnlCarteJeu;
    private javax.swing.JPanel pnlInformation;
    private javax.swing.JPanel pnlStatut;
    private javax.swing.JTextArea txtDescriptionCarte1;
    private javax.swing.JTextArea txtDescriptionCarte2;
    private javax.swing.JTextArea txtDescriptionCarte3;
    private javax.swing.JTextArea txtDescriptionCarte4;
    private javax.swing.JTextArea txtDescriptionCarte5;
    private javax.swing.JTextArea txtDescriptionCarteChoisi;
    private javax.swing.JTextArea txtDescriptionCarteJeu;
    private javax.swing.JTextArea txtEvenement;
    // End of variables declaration//GEN-END:variables

    /*
     * Change l'écran pour se conformer avec les changements de la partie
     * *important* Appeler à chaque changement *important*
     */
    public void updateInterfaceJeu() {
        Player player = (Player)partie.getPlayers().get(0);
        Card card;
        ImageIcon img;
        Image dimg;
        
        lblTour.setText(Integer.toString(partie.getNbTours()));
        lblPaquet.setText(Integer.toString(partie.getCards().size()));
        lblTalon.setText(Integer.toString(partie.getDiscardedCards().size()));
        
        lblPtsVie1.setText(Integer.toString(player.getHitPoints()));
        if (player.getFactories().size() >= 1) {
            lblUsineUn1.setText("Attaque + " + player.getFactories().get(0).getAttackFactor());
        } else {
            lblUsineUn1.setText("Usine");
        }
        if (player.getFactories().size() >= 2) {
            lblUsineDeux1.setText("Attaque +" + player.getFactories().get(1).getAttackFactor());
        } else {
            lblUsineDeux1.setText("Usine");
        }
        if (player.getResearchCenter() != null) {
            if (player.getResearchCenter().getDefenceFactor() > 0)
                lblRecherche1.setText("Défense +" + player.getResearchCenter().getDefenceFactor());
            else
                lblRecherche1.setText("Attaque +" + player.getResearchCenter().getAttackFactor());
        } else {
            lblRecherche1.setText("Recherche");
        }
        
        if (player.getCards().size() >= 1) {
            card = player.getCards().get(0);
            lblNomCarte1.setText(card.getName());
            img = card.getImage();
            dimg = (img.getImage()).getScaledInstance(80, 70,
                Image.SCALE_SMOOTH);
            img = new ImageIcon(dimg);
            lblImgCarte1.setIcon(img);
            txtDescriptionCarte1.setText(card.getDescription());
        } else {
            lblNomCarte1.setText("");
            lblImgCarte1.setIcon(null);
            txtDescriptionCarte1.setText("");
        }
        
        if (player.getCards().size() >= 1) {
            card = player.getCards().get(0);
            lblNomCarte1.setText(card.getName());
            lblImgCarte1.setIcon(card.getImage());
            txtDescriptionCarte1.setText(card.getDescription());
        } else {
            lblNomCarte1.setText("");
            lblImgCarte1.setIcon(null);
            txtDescriptionCarte1.setText("");
        }
        
       if (player.getCards().size() >= 2) {
            card = player.getCards().get(1);
            lblNomCarte2.setText(card.getName());
            lblImgCarte2.setIcon(card.getImage());
            txtDescriptionCarte2.setText(card.getDescription());
        } else {
            lblNomCarte2.setText("");
            lblImgCarte2.setIcon(null);
            txtDescriptionCarte2.setText("");
        }
        
        if (player.getCards().size() >= 3) {
            card = player.getCards().get(2);
            lblNomCarte3.setText(card.getName());
            lblImgCarte3.setIcon(card.getImage());
            txtDescriptionCarte3.setText(card.getDescription());
        } else {
            lblNomCarte3.setText("");
            lblImgCarte3.setIcon(null);
            txtDescriptionCarte3.setText("");
        }
        
        if (player.getCards().size() >= 4) {
            card = player.getCards().get(3);
            lblNomCarte4.setText(card.getName());
            lblImgCarte4.setIcon(card.getImage());
            txtDescriptionCarte4.setText(card.getDescription());
        } else {
            lblNomCarte4.setText("");
            lblImgCarte4.setIcon(null);
            txtDescriptionCarte4.setText("");
        }
        
        if (player.getCards().size() >= 5) {
            card = player.getCards().get(4);
            lblNomCarte5.setText(card.getName());
            lblImgCarte5.setIcon(card.getImage());
            txtDescriptionCarte5.setText(card.getDescription());
        } else {
            lblNomCarte5.setText("");
            lblImgCarte5.setIcon(null);
            txtDescriptionCarte5.setText("");
        }
        
        if (partie.getPlayers().size() >= 2) {
            player = (Player)partie.getPlayers().get(1);
            if (player.getFactories().size() >= 1) {
                lblUsineUn2.setText("Attaque + " + player.getFactories().get(0).getAttackFactor());
            } else {
                lblUsineUn2.setText("Usine");
            }
            if (player.getFactories().size() >= 2) {
                lblUsineDeux2.setText("Attaque +" + player.getFactories().get(1).getAttackFactor());
            } else {
                lblUsineDeux2.setText("Usine");
            }
            if (player.getResearchCenter() != null) {
                if (player.getResearchCenter().getDefenceFactor() > 0)
                    lblRecherche2.setText("Défense +" + player.getResearchCenter().getDefenceFactor());
                else
                    lblRecherche2.setText("Attaque +" + player.getResearchCenter().getAttackFactor());
            } else {
                lblRecherche2.setText("Recherche");
            }
            lblPtsVie2.setText(Integer.toString(player.getHitPoints()));
            lblCarteEnMain2.setText(Integer.toString(player.getCards().size()));
        }
        
        if (partie.getPlayers().size() >= 3) {
            player = (Player)partie.getPlayers().get(2);
            if (player.getFactories().size() >= 1) {
                lblUsineUn3.setText("Attaque + " + player.getFactories().get(0).getAttackFactor());
            } else {
                lblUsineUn3.setText("Usine");
            }
            if (player.getFactories().size() >= 2) {
                lblUsineDeux3.setText("Attaque +" + player.getFactories().get(1).getAttackFactor());
            } else {
                lblUsineDeux3.setText("Usine");
            }
            if (player.getResearchCenter() != null) {
                if (player.getResearchCenter().getDefenceFactor() > 0)
                    lblRecherche3.setText("Défense +" + player.getResearchCenter().getDefenceFactor());
                else
                    lblRecherche3.setText("Attaque +" + player.getResearchCenter().getAttackFactor());
            } else {
                lblRecherche3.setText("Recherche");
            }
            lblPtsVie3.setText(Integer.toString(player.getHitPoints()));
            lblCarteEnMain3.setText(Integer.toString(player.getCards().size()));
        }
        
        if (partie.getPlayers().size() >= 4) {
            player = (Player)partie.getPlayers().get(3);
            if (player.getFactories().size() >= 1) {
                lblUsineUn4.setText("Attaque + " + player.getFactories().get(0).getAttackFactor());
            } else {
                lblUsineUn4.setText("Usine");
            }
            if (player.getFactories().size() >= 2) {
                lblUsineDeux4.setText("Attaque +" + player.getFactories().get(1).getAttackFactor());
            } else {
                lblUsineDeux4.setText("Usine");
            }
            if (player.getResearchCenter() != null) {
                if (player.getResearchCenter().getDefenceFactor() > 0)
                    lblRecherche4.setText("Défense +" + player.getResearchCenter().getDefenceFactor());
                else
                    lblRecherche4.setText("Attaque +" + player.getResearchCenter().getAttackFactor());
            } else {
                lblRecherche4.setText("Recherche");
            }
            lblPtsVie4.setText(Integer.toString(player.getHitPoints()));
            lblCarteEnMain4.setText(Integer.toString(player.getCards().size()));
        }
        
        frame.revalidate();
        frame.repaint();
        frame.setVisible(true);
    }
    
    /*
     * Rend tous les éléments inactifs
     */
    public void lockAllPhase() {
        PnlAdversaire1.setEnabled(false);
        PnlAdversaire2.setEnabled(false);
        PnlAdversaire3.setEnabled(false);
        PnlAdversaire1.setBackground(defaut);
        PnlAdversaire2.setBackground(defaut);
        PnlAdversaire3.setBackground(defaut);
        PnlInfoPersonnel.setBackground(defaut);
        
        pnlCarte1.setEnabled(false);
        pnlCarte2.setEnabled(false);
        pnlCarte3.setEnabled(false);
        pnlCarte4.setEnabled(false);
        pnlCarte5.setEnabled(false);
        pnlCarte1.setBackground(defaut);
        pnlCarte2.setBackground(defaut);
        pnlCarte3.setBackground(defaut);
        pnlCarte4.setBackground(defaut);
        pnlCarte5.setBackground(defaut);
        
        btnAction1.setText("jouer");
        btnAction2.setText("Passer");
        btnAction1.setEnabled(false);
        btnAction2.setEnabled(false);
        
        //lblUsineUn1.setEnabled(false);
        lblUsineUn1.setForeground(Color.BLACK);
        //lblUsineDeux1.setEnabled(false);
        lblUsineDeux1.setForeground(Color.BLACK);
        
        lblDommage1.setText("");
        lblDommage2.setText("");
        lblDommage3.setText("");
        lblDommage4.setText("");
        
        lblCarteChoisi.setText("");
        lblImgCarteChoisi.setIcon(null);
        txtDescriptionCarteChoisi.setText("");
        
        frame.revalidate();
        frame.repaint();
        frame.setVisible(true);
    }
    
    /*
     * Débute la phase d'attaque
     */
    public void unlockAttackPhase(boolean attackCards[]) {
        phaseJeu = Phase.ATTAQUE;
        selection = 0;
        //btnAction2.setEnabled(true);
        
        if (attackCards[0]) {
            pnlCarte1.setEnabled(true);
            pnlCarte1.setBackground(actif);
        }
        if (attackCards[1]) {
            pnlCarte2.setEnabled(true);
            pnlCarte2.setBackground(actif);
        }
        if (attackCards[2]) {
            pnlCarte3.setEnabled(true);
            pnlCarte3.setBackground(actif);
        }
        if (attackCards[3]) {
            pnlCarte4.setEnabled(true);
            pnlCarte4.setBackground(actif);
        }
        if (attackCards[4]) {
            pnlCarte5.setEnabled(true);
            pnlCarte5.setBackground(actif);
        }
    }
    
    /*
     * débute la phase choisir un target
     */
    public void unlockTargetingPhase(boolean aliveOpponents[]) {
        phaseJeu = Phase.TARGETING;
        if (aliveOpponents.length >= 1)
            if (aliveOpponents[0]) {
                PnlAdversaire1.setEnabled(true);
                PnlAdversaire1.setBackground(actif);
            }
        
        if (aliveOpponents.length >= 2)
            if (aliveOpponents[1]) {
                PnlAdversaire2.setEnabled(true);
                PnlAdversaire2.setBackground(actif);
            }
        
        if (aliveOpponents.length >= 3)
            if (aliveOpponents[2]) {
                PnlAdversaire3.setEnabled(true);
                PnlAdversaire3.setBackground(actif);
            }
    }
    
    /*
     * débute la phase défense
     */
    public void unlockDefensePhase(boolean defenseCards[]) {
        
    }
    
    /*
     * débute la phase choisir factory à discarder si il y a lieu
     */
    public void unlockFactoryPhase() {
    }
    
    /*
     * débute phase passer le tour
     */
    public void unlockPassPhase() {
        phaseJeu = Phase.PASSE;
        selection = 0;
        btnAction1.setText("Défausser");
        btnAction2.setEnabled(false);
        
        pnlCarte1.setEnabled(true);
        pnlCarte1.setBackground(actif);

        pnlCarte2.setEnabled(true);
        pnlCarte2.setBackground(actif);

        pnlCarte3.setEnabled(true);
        pnlCarte3.setBackground(actif);

        pnlCarte4.setEnabled(true);
        pnlCarte4.setBackground(actif);

        pnlCarte5.setEnabled(true);
        pnlCarte5.setBackground(actif);
        
    }
    
    public void unlockContinuePhase(){
        phaseJeu = Phase.CONTINUER;
        btnAction1.setText("Continuer");
        btnAction1.setEnabled(true);
    }

    /*
     * description du tour du joueur
     */
    public void AnnouncePlayerAction(String announce) {
        txtEvenement.append(announce);
        txtEvenement.setCaretPosition(txtEvenement.getDocument().getLength());
    }
    
    public void endGame(int winner) {
        JOptionPane.showConfirmDialog(this, "Le gagnant est le joueur " + (winner + 1));
        this.setVisible(false);
        new MenuPrincipal().start();
        this.dispose();
    }
    
    public void showDamage(int damage, int cible) {
        if (cible == 1)
            lblDommage2.setText("-" + damage);
        else if (cible == 2)
            lblDommage3.setText("-" + damage);
        else if (cible == 3)
            lblDommage4.setText("-" + damage);
        else if (cible == 0)
            lblDommage1.setText("-" + damage);
    }
    
    public void showOpponentAttack(Card carte, int cible, int lanceur) {
        lblCarteEnJeu.setText(carte.getName());
        lblImgCarteJeu.setIcon(carte.getImage());
        txtDescriptionCarteJeu.setText(carte.getDescription());
        
        if (lanceur == 0) {
            PnlInfoPersonnel.setBackground(actif);
        }
        else if (lanceur == 1) {
            PnlAdversaire1.setBackground(actif);
        }
        else if (lanceur == 2) {
            PnlAdversaire2.setBackground(actif);
        }
        else if (lanceur == 3) {
            PnlAdversaire3.setBackground(actif);
        }
        
        if (cible == 1)
            PnlAdversaire1.setBackground(attaque);
        else if (cible == 2)
            PnlAdversaire2.setBackground(attaque);
        else if (cible == 3)
            PnlAdversaire3.setBackground(attaque);
        else if (cible == 0)
            PnlInfoPersonnel.setBackground(attaque);
        else if (cible == -1) {
            if (lanceur != 0) {
                PnlInfoPersonnel.setBackground(attaque);
            }
            if (lanceur != 1) {
                PnlAdversaire1.setBackground(attaque);
            }
            if (lanceur != 2) {
                PnlAdversaire2.setBackground(attaque);
            }
            if (lanceur != 3) {
                PnlAdversaire3.setBackground(attaque);
            }
        }
        
        if (cible == -1)
            AnnouncePlayerAction("\nLe joueur " + (lanceur + 1) + " a joué " + carte.getName() + " sur tous les opposants");
        else
            AnnouncePlayerAction("\nLe joueur " + (lanceur + 1) + " a joué " + carte.getName() + " sur le joueur " + (cible + 1));
        
        frame.revalidate();
        frame.repaint();
        frame.setVisible(true);
    }
   
}
