/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mad.views;

/**
 *
 * @author Francois
 */
public class VuePartie extends javax.swing.JFrame {

    /**
     * Creates new form VuePartie
     */
    public VuePartie() {
        initComponents();
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VuePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlPartie = new javax.swing.JPanel();
        PnlAdversaire1 = new javax.swing.JPanel();
        lblJoueur2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblUsineDeux2 = new javax.swing.JLabel();
        lblUsineUn2 = new javax.swing.JLabel();
        lblRecherche2 = new javax.swing.JLabel();
        lblPtsVie2 = new javax.swing.JLabel();
        lblCarteEnMain2 = new javax.swing.JLabel();
        PnlAdversaire2 = new javax.swing.JPanel();
        lblJoueur3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPtsVie3 = new javax.swing.JLabel();
        lblCarteEnMain3 = new javax.swing.JLabel();
        lblUsineUn3 = new javax.swing.JLabel();
        lblUsineDeux3 = new javax.swing.JLabel();
        lblRecherche3 = new javax.swing.JLabel();
        PnlAdversaire3 = new javax.swing.JPanel();
        lblJoueur4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPtsVie4 = new javax.swing.JLabel();
        lblCarteEnMain4 = new javax.swing.JLabel();
        lblUsineUn4 = new javax.swing.JLabel();
        lblUsineDeux4 = new javax.swing.JLabel();
        lblRecherche4 = new javax.swing.JLabel();
        PnlInfoPersonnel = new javax.swing.JPanel();
        txtCarteSelectionnee = new javax.swing.JTextField();
        btnAction1 = new javax.swing.JButton();
        btnAction2 = new javax.swing.JButton();
        txtCarte1 = new javax.swing.JTextField();
        txtCarte3 = new javax.swing.JTextField();
        txtCarte4 = new javax.swing.JTextField();
        txtCarte2 = new javax.swing.JTextField();
        txtCarte5 = new javax.swing.JTextField();
        lblJoueur1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPtsVie1 = new javax.swing.JLabel();
        lblUsineUn1 = new javax.swing.JLabel();
        lblUsineDeux1 = new javax.swing.JLabel();
        lblRecherche1 = new javax.swing.JLabel();
        PnlCarteEnJeu = new javax.swing.JPanel();
        txtCarteJeu = new javax.swing.JTextField();
        pnlStatut = new javax.swing.JPanel();
        txtEvenement = new javax.swing.JTextField();
        pnlInformation = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblTour = new javax.swing.JLabel();
        lblPaquet = new javax.swing.JLabel();
        lblTalon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("M.A.D. Partie");
        setResizable(false);

        PnlPartie.setBackground(new java.awt.Color(153, 153, 255));

        PnlAdversaire1.setPreferredSize(new java.awt.Dimension(485, 100));

        lblJoueur2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJoueur2.setText("Joueur 2");

        jLabel1.setText("Points de vie : ");

        jLabel5.setText("Cartes en main:");

        lblUsineDeux2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineDeux2.setText("Usine 2");
        lblUsineDeux2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsineUn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineUn2.setText("Usine 1");
        lblUsineUn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRecherche2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecherche2.setText("Recherche");
        lblRecherche2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPtsVie2.setText("50");

        lblCarteEnMain2.setText("5");

        javax.swing.GroupLayout PnlAdversaire1Layout = new javax.swing.GroupLayout(PnlAdversaire1);
        PnlAdversaire1.setLayout(PnlAdversaire1Layout);
        PnlAdversaire1Layout.setHorizontalGroup(
            PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJoueur2)
                    .addGroup(PnlAdversaire1Layout.createSequentialGroup()
                        .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarteEnMain2)
                            .addComponent(lblPtsVie2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsineUn2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblUsineDeux2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRecherche2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        PnlAdversaire1Layout.setVerticalGroup(
            PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblUsineUn2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlAdversaire1Layout.createSequentialGroup()
                        .addComponent(lblJoueur2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblPtsVie2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAdversaire1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblCarteEnMain2)))
                    .addComponent(lblRecherche2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsineDeux2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        PnlAdversaire2.setPreferredSize(new java.awt.Dimension(99, 100));

        lblJoueur3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJoueur3.setText("Joueur 3");

        jLabel2.setText("Points de vie : ");

        jLabel6.setText("Cartes en main:");

        lblPtsVie3.setText("50");

        lblCarteEnMain3.setText("5");

        lblUsineUn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineUn3.setText("Usine 1");
        lblUsineUn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsineDeux3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineDeux3.setText("Usine 2");
        lblUsineDeux3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRecherche3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecherche3.setText("Recherche");
        lblRecherche3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PnlAdversaire2Layout = new javax.swing.GroupLayout(PnlAdversaire2);
        PnlAdversaire2.setLayout(PnlAdversaire2Layout);
        PnlAdversaire2Layout.setHorizontalGroup(
            PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJoueur3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarteEnMain3)
                    .addComponent(lblPtsVie3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblUsineUn3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsineDeux3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRecherche3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        PnlAdversaire2Layout.setVerticalGroup(
            PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlAdversaire2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlAdversaire2Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(lblPtsVie3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCarteEnMain3))
                        .addComponent(lblUsineUn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRecherche3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsineDeux3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlAdversaire2Layout.createSequentialGroup()
                        .addComponent(lblJoueur3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblJoueur4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJoueur4.setText("Joueur 4");

        jLabel3.setText("Points de vie : ");

        jLabel7.setText("Cartes en main:");

        lblPtsVie4.setText("50");

        lblCarteEnMain4.setText("5");

        lblUsineUn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineUn4.setText("Usine 1");
        lblUsineUn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsineDeux4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineDeux4.setText("Usine 2");
        lblUsineDeux4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRecherche4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecherche4.setText("Recherche");
        lblRecherche4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PnlAdversaire3Layout = new javax.swing.GroupLayout(PnlAdversaire3);
        PnlAdversaire3.setLayout(PnlAdversaire3Layout);
        PnlAdversaire3Layout.setHorizontalGroup(
            PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJoueur4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarteEnMain4)
                    .addComponent(lblPtsVie4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsineUn4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsineDeux4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRecherche4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        PnlAdversaire3Layout.setVerticalGroup(
            PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdversaire3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlAdversaire3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlAdversaire3Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(lblPtsVie4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCarteEnMain4))
                        .addComponent(lblUsineUn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRecherche4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsineDeux4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlAdversaire3Layout.createSequentialGroup()
                        .addComponent(lblJoueur4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        PnlInfoPersonnel.setPreferredSize(new java.awt.Dimension(285, 392));

        txtCarteSelectionnee.setEditable(false);
        txtCarteSelectionnee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCarteSelectionnee.setText("Carte Sélectionnée");

        btnAction1.setText("Jouer");

        btnAction2.setText("Passer");

        txtCarte1.setEditable(false);
        txtCarte1.setText("Carte1");

        txtCarte3.setEditable(false);
        txtCarte3.setText("Carte3");

        txtCarte4.setEditable(false);
        txtCarte4.setText("Carte4");

        txtCarte2.setEditable(false);
        txtCarte2.setText("Carte2");

        txtCarte5.setEditable(false);
        txtCarte5.setText("Carte5");

        lblJoueur1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJoueur1.setText("Joueur 1");

        jLabel4.setText("Points de vie : ");

        lblPtsVie1.setText("50");

        lblUsineUn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineUn1.setText("Usine 1");
        lblUsineUn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsineDeux1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsineDeux1.setText("Usine 2");
        lblUsineDeux1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRecherche1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecherche1.setText("Recherche");
        lblRecherche1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PnlInfoPersonnelLayout = new javax.swing.GroupLayout(PnlInfoPersonnel);
        PnlInfoPersonnel.setLayout(PnlInfoPersonnelLayout);
        PnlInfoPersonnelLayout.setHorizontalGroup(
            PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCarteSelectionnee, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                        .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAction2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                                .addComponent(btnAction1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJoueur1)
                                    .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPtsVie1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsineUn1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUsineDeux1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRecherche1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                        .addComponent(txtCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCarte2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCarte3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCarte4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCarte5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        PnlInfoPersonnelLayout.setVerticalGroup(
            PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                        .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                                .addComponent(btnAction1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAction2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlInfoPersonnelLayout.createSequentialGroup()
                                .addComponent(lblJoueur1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lblPtsVie1)))
                            .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblUsineUn1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUsineDeux1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRecherche1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlInfoPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarte2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarte3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarte4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarte5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtCarteSelectionnee))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCarteJeu.setEditable(false);
        txtCarteJeu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCarteJeu.setText("Carte en jeu");

        javax.swing.GroupLayout PnlCarteEnJeuLayout = new javax.swing.GroupLayout(PnlCarteEnJeu);
        PnlCarteEnJeu.setLayout(PnlCarteEnJeuLayout);
        PnlCarteEnJeuLayout.setHorizontalGroup(
            PnlCarteEnJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCarteEnJeuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCarteJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlCarteEnJeuLayout.setVerticalGroup(
            PnlCarteEnJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCarteEnJeuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCarteJeu, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtEvenement.setEditable(false);
        txtEvenement.setText("Évènement");

        javax.swing.GroupLayout pnlStatutLayout = new javax.swing.GroupLayout(pnlStatut);
        pnlStatut.setLayout(pnlStatutLayout);
        pnlStatutLayout.setHorizontalGroup(
            pnlStatutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEvenement)
                .addContainerGap())
        );
        pnlStatutLayout.setVerticalGroup(
            pnlStatutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEvenement, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel24.setText("Tour:");

        jLabel28.setText("Paquet :");

        jLabel29.setText("Talon :");

        lblTour.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTour.setText("31");

        lblPaquet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPaquet.setText("31");

        lblTalon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTalon.setText("31");

        javax.swing.GroupLayout pnlInformationLayout = new javax.swing.GroupLayout(pnlInformation);
        pnlInformation.setLayout(pnlInformationLayout);
        pnlInformationLayout.setHorizontalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTour, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTalon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPaquet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlInformationLayout.setVerticalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblTour))
                .addGap(18, 18, 18)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblPaquet))
                .addGap(18, 18, 18)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblTalon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlPartieLayout = new javax.swing.GroupLayout(PnlPartie);
        PnlPartie.setLayout(PnlPartieLayout);
        PnlPartieLayout.setHorizontalGroup(
            PnlPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlPartieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlStatut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PnlPartieLayout.createSequentialGroup()
                        .addComponent(PnlCarteEnJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PnlAdversaire3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PnlAdversaire2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                            .addComponent(PnlAdversaire1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(PnlInfoPersonnel, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE))
                .addContainerGap())
        );
        PnlPartieLayout.setVerticalGroup(
            PnlPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPartieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlPartieLayout.createSequentialGroup()
                        .addComponent(PnlAdversaire1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PnlAdversaire2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PnlAdversaire3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PnlCarteEnJeu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnlInfoPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPartie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPartie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void start() {
        final VuePartie me = this;
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                me.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlAdversaire1;
    private javax.swing.JPanel PnlAdversaire2;
    private javax.swing.JPanel PnlAdversaire3;
    private javax.swing.JPanel PnlCarteEnJeu;
    private javax.swing.JPanel PnlInfoPersonnel;
    private javax.swing.JPanel PnlPartie;
    private javax.swing.JButton btnAction1;
    private javax.swing.JButton btnAction2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCarteEnMain2;
    private javax.swing.JLabel lblCarteEnMain3;
    private javax.swing.JLabel lblCarteEnMain4;
    private javax.swing.JLabel lblJoueur1;
    private javax.swing.JLabel lblJoueur2;
    private javax.swing.JLabel lblJoueur3;
    private javax.swing.JLabel lblJoueur4;
    private javax.swing.JLabel lblPaquet;
    private javax.swing.JLabel lblPtsVie1;
    private javax.swing.JLabel lblPtsVie2;
    private javax.swing.JLabel lblPtsVie3;
    private javax.swing.JLabel lblPtsVie4;
    private javax.swing.JLabel lblRecherche1;
    private javax.swing.JLabel lblRecherche2;
    private javax.swing.JLabel lblRecherche3;
    private javax.swing.JLabel lblRecherche4;
    private javax.swing.JLabel lblTalon;
    private javax.swing.JLabel lblTour;
    private javax.swing.JLabel lblUsineDeux1;
    private javax.swing.JLabel lblUsineDeux2;
    private javax.swing.JLabel lblUsineDeux3;
    private javax.swing.JLabel lblUsineDeux4;
    private javax.swing.JLabel lblUsineUn1;
    private javax.swing.JLabel lblUsineUn2;
    private javax.swing.JLabel lblUsineUn3;
    private javax.swing.JLabel lblUsineUn4;
    private javax.swing.JPanel pnlInformation;
    private javax.swing.JPanel pnlStatut;
    private javax.swing.JTextField txtCarte1;
    private javax.swing.JTextField txtCarte2;
    private javax.swing.JTextField txtCarte3;
    private javax.swing.JTextField txtCarte4;
    private javax.swing.JTextField txtCarte5;
    private javax.swing.JTextField txtCarteJeu;
    private javax.swing.JTextField txtCarteSelectionnee;
    private javax.swing.JTextField txtEvenement;
    // End of variables declaration//GEN-END:variables
}
